BLOCK_SITE:
- https://hexo.io/
DATABASE: mongodb
DEPLOY_TYPE: github
GITEE_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: blogroll
  state: open
  type: normal
GITHUB_FRIENDS_LINKS:
  enable: false
  label: active
  owner: ccknbc
  repo: ccknbc-actions
  state: open
  type: normal
HTTP_PROXY: false
LINK:
- link: https://blog.sinzmise.top/link/
  theme: common2
MAX_POSTS_NUM: 5
OUTDATE_CLEAN: 60
SETTINGS_FRIENDS_LINKS:
  enable: true
  json_api: ''
  list:
  - - MHuiG
    - https://blog.mhuig.top/
    - https://jsd.cdn.sininno.eu.org/npm/mhg@latest
  - - "\u751C\u9C7C/Ayu"
    - https://ayu.land/
    - https://ayu.land/about/Ayu.jpg
    - atom.zh.xml
  - - "Ading\u963F\u5B9A\u306E\u5C0F\u7AD9"
    - https://blog.saop.cc/
    - https://picbed.saop.cc/Asuna/Asuna1x1.png
